name: flask_func_struct_vue triage
on:
  issues:
    types: [opened]
jobs:
  commentOnNewIssues:
    name: flask_func_struct_vue triage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: flask_func_struct_vue triage
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment "[flask_func_struct_vue] should be supported for Python 2.7"
